### ISSUE TITLE
Anzeige Anzahl neuer Inhalte auf Nutzer Mappen

### ISSUE THREAD

**Issue by VischoolA** [ViSchool/laravi#34]
Beispiel: Gleichungen hat 10 Inhalte. Allerdings nur privat veröffentlicht. Alle anderen sehen die Anzeige "10 neue Inhalte", wenn sie drauf klicken, gibt es aber 0 Inhalte (weil nicht öffentlich).

**Comment by karistokrat** [comment]
bei den privaten Themen sieht man jetzt alle Inhalte gezählt, bei den öffentlichen nur die öffentlichen...
