### ISSUE TITLE
Als Lehrer nach Eingabe neuer Aufgabe zur Übersicht der Aufgaben springen

### ISSUE THREAD

**Issue by VischoolA** [ViSchool/laravi#35]
Im Moment ist es so, dass man nach Anlegen einer neuer Aufgabe in einer Lerneinheit wieder auf die Seite mit der Übersicht aller Lerneinheiten kommt. Besser wäre, auf die Seite mit der Unterrichtseinheit und der Übersicht über die verschiedenen Aufgaben pro Lerneinheit zu gelangen

**Comment by karistokrat** [comment]
Ist erledigt.
