### ISSUE TITLE
Ansicht Lerneinheit bei H5P Inhalt verbessern

### ISSUE THREAD

**Issue by VischoolA** [ViSchool/laravi#36]
Ansicht bei Aufgaben mit Videos ist ok. Aber H5P eingebundene Inhalte werden nicht optimal dargestellt. Beispiel: https://vischool.net/lerneinheit/38

**Comment by karistokrat** [comment]
Ist erstmal angepasst mit Text der Aufgabe und PlayButton, wenn kein Bild hinterlegt ist. Müssen wir noch mal die einzelnen Tools durchgehen, wenn mal Zeit ist.
