### ISSUE TITLE
Differenzierung in Safari schwer anlegebar

### ISSUE THREAD

**Issue by VischoolA** [ViSchool/laravi#51]
Beim Anlegen einer neuen Differenzierung auf der Lehrerseite öffnet sich ein enges Kästchen, in dem der Titel der Differenzierung noch eintragbar ist (auch eng), aber für die einzelnen Niveaus sind nur kleine Kästchen (Größe Matheheft Kästchen) da, bei denen man nicht sieht, was man einträgt. Drunter steht noch  ein Kästchen in dem wahrscheinlich etwas von 5. Fach steht, kann man aber auch kaum lesen. Parameter für Rahmen überprüfen?

**Comment by karistokrat** [comment]
Gesehen, schaue ich mir an

**Comment by karistokrat** [comment]
Erledigt, ist wieder hübsch
