### ISSUE TITLE
FAQs im Backend editierbar machen

### ISSUE THREAD

**Issue by VischoolA** [ViSchool/laravi#52]
Habe gerade den ersten Eintrag vorgenommen und nach Eintrag gemerkt, dass ich mich vertippt hatte. Wäre prima, wenn ich Einträge später noch editieren könnte.

**Comment by karistokrat** [comment]
Funktioniert schon, einfach in der Übersicht aller Fragen auf die Frage klicken und beliebig ändern. Solange und sooft Du willst.  ;-)
