### ISSUE TITLE
Differenzierung wird nicht korrekt in Lerneinheit angezeigt

### ISSUE THREAD

**Issue by VischoolA** [ViSchool/laravi#53]
Gleich mehrere Probleme:
1. Einmal angelegte Differenzierung bei einer Lerneinheit nicht mehr rückgängig zu machen: Ich hatte in einer Lerneinheit zuerst meine neue Differenzierung "Hagerhof" angegeben, dann aber die Lerneinheit geändert und "keine Differenzierung" angegeben. Wenn ich dann aber Aufgaben anlege, muss ich doch Differenzierungen angeben.
2. Ganz spooky: wenn ich dann "alle" angebe, tauchen letztlich gar nicht die Differenzierungen vom Hagerhof auf, sondern "leicht, mittel, schwer" (wo kommt das denn her? Ist in meinem Lehrerprofil gar nicht hinterlegt).

**Comment by karistokrat** [comment]
Ist wieder erledigt, siehe auch Hinweise bei Slack im github Channel.
