### ISSUE TITLE
Neuer Inhalt im Backend als Thema angelegt?

### ISSUE THREAD

**Issue by VischoolA** [ViSchool/laravi#56]
Schau mal ins Backend. Hier taucht "Terme" als neues THEMA auf. Habe ich aber gar nicht ein 2. mal als Thema angelegt. (Das Thema Terme gibt es schon längst).  Ich vermute, dass die Anlage eines neuen INHALTS nicht über Inhalt anlegen sondern innerhalb der Lerneinheit neu anlegt als neues THEMA statt neuer Inhalt interpretiert wird. Kann das sein?

**Comment by karistokrat** [comment]
Fehler gefunden und behoben!
