### ISSUE TITLE
Lerneinheit auch wenn privat veröffentlicht bearbeitbare machen

### ISSUE THREAD

**Issue by VischoolA** [ViSchool/laravi#60]
Als Lehrer kann ich meine Lerneinheit nicht mehr ändern, sobald ich sie privat veröffentlicht habe. Wäre aber prima, wenn das doch  noch ginge.

**Comment by karistokrat** [comment]
Habe ich geändert. Ich weiß gerade nicht mehr warum ich es so eingestellt hatte. Da es mir nicht mehr eingefallen ist... Funktioniert wohl auch, alle Tests bei mir ok.
