### ISSUE TITLE
Aufgaben ändern wird nicht angenommen

### ISSUE THREAD

**Issue by VischoolA** [ViSchool/laravi#62]
Wenn ich später nochmal eine angelegte Aufgabe ändern möchte (z.B. anderes Video einbetten oder Überschrift ändern, Tippfehler etc.) komme ich zwar rein und kann ändern, aber die Änderungen werden nicht angenommen.

**Comment by karistokrat** [comment]
Sollte nun hoffentlich gelöst sein.
