### ISSUE TITLE
Aktualisierung Aufgaben nach Überarbeitung funktioniert nicht

### ISSUE THREAD

**Issue by VischoolA** [ViSchool/laravi#66]
Irgendwie funktioniert es noch nicht, wenn ich bei Aufgaben etwas aktualisieren. So habe ich in der ersten Lerneinheit bei Termen "Erstelle einen Term" versucht, bei der ersten Aufgabe einen Inhalt einzufügen. Das wurde aber nicht angenommen.

**Comment by karistokrat** [comment]
Funktioniert wieder, war nur Datenbankproblem
