### ISSUE TITLE
Lehrerinhalt bearbeitbare machen

### ISSUE THREAD

**Issue by VischoolA** [ViSchool/laravi#74]
Wunsch: Privat veröffentlichte Inhalte sollte der Lehrer nochmal editieren dürfen (z.B. Titel ändern). Beispiel: https://vischool.net/lehrer/inhalte => Außer "an die ViSchool senden" sollte es noch Button "bearbeiten" geben.

**Comment by karistokrat** [comment]
Erledigt, Inhalte können jetzt bearbeitet und gelöscht werden.
