### ISSUE TITLE
Lehrer bearbeiten eigenen Inhalt - klappt noch nicht

### ISSUE THREAD

**Issue by VischoolA** [ViSchool/laravi#80]
Wenn ich als Lehrer einen von mir erstellten Inhalt (nur privat veröffentlicht) anklicke, um ihn zu bearbeiten, erscheint zwar genau das Formular, das ich gerne bearbeiten will, allerdings ausgefüllt mit einem Dummy-Inhalt aus Physik, nicht mit dem von mir angeklickten Inhalt.

**Comment by karistokrat** [comment]
Geht wieder, Fehler hoffentlich behoben und nun auch hochgeladen....
