### ISSUE TITLE
Inhalte in Lerneinheit einstellen - Fehler

### ISSUE THREAD

**Issue by VischoolA** [ViSchool/laravi#81]
Lustiger Fehler: Ich habe gerade in einer kopierten Lerneinheit mit verschiedenen Aufgaben bei einer Aufgabe einen neuen Inhalt eingefügt, indem ich nicht etwa einen bereits existierenden Inhalt eingefügt habe, sondern indem ich den Button "neuen Inhalt erstellen" genutzt habe. Hat auch prima funktioniert. Allerdings wurde der Inhalt gleich bei allen Aufgaben der Lerneinheit nun eingefügt, nicht nur in der von mir bearbeiteten Aufgabe.

**Comment by karistokrat** [comment]
Das funktioniert jetzt auch wieder, Fehler war nur beim Ändern einer Aufgabe. Jetzt sollte es aber richtig funktionieren.
