### ISSUE TITLE
Aufträge Schüler - bei Start Formular Login 

### ISSUE THREAD

**Issue by VischoolA** [ViSchool/laravi#85]
Ich bin als Schüler eingeloggt und auf meiner Seite mit den Aufträgen. Wenn ich auf „Start“ gehe, komme ich auf eine Seite, wo ich mich mit eMail einloggen soll, obwohl ich doch bereits mit meinem Schüleraccount (Warlock) eingeloggt bin

**Comment by karistokrat** [comment]
Sollte jetzt wieder funktionieren.
